import type { AgencyData, Motorcycle } from "@/lib/types";

const importedAt = "2026-06-10T20:10:00.000Z";
const defaultImage = "/re-motos-logo.jpeg";

const priceListMotorcycles: Motorcycle[] = [
  {
    id: "moto-motomel-blitz-base-110-gris",
    brand: "Motomel",
    model: "Blitz base 110 gris",
    category: "Cub",
    price: 1730000,
    currency: "ARS",
    cost: 0,
    stock: 1,
    branch: "RE Motos",
    status: "Últimas unidades",
    image: defaultImage,
    cardInstallments: { 3: 645866, 6: 343116, 12: 196066, 18: 152816 },
    updatedAt: importedAt,
  },
  {
    id: "moto-motomel-blitz-full-110-azul",
    brand: "Motomel",
    model: "Blitz aleacion full 110 azul",
    category: "Cub",
    price: 2030000,
    currency: "ARS",
    cost: 0,
    stock: 1,
    branch: "RE Motos",
    status: "Últimas unidades",
    image: defaultImage,
    cardInstallments: { 3: 757866, 6: 402616, 12: 230066, 18: 179316 },
    updatedAt: importedAt,
  },
  {
    id: "moto-gilera-smash-base-110-azul",
    brand: "Gilera",
    model: "Smash base 110 azul",
    category: "Cub",
    price: 1800000,
    currency: "ARS",
    cost: 0,
    stock: 1,
    branch: "RE Motos",
    status: "Últimas unidades",
    image: defaultImage,
    cardInstallments: { 3: 672000, 6: 357000, 12: 204000, 18: 159000 },
    updatedAt: importedAt,
  },
  {
    id: "moto-gilera-smash-full-110-roja",
    brand: "Gilera",
    model: "Smash full 110 roja",
    category: "Cub",
    price: 2260000,
    currency: "ARS",
    cost: 0,
    stock: 1,
    branch: "RE Motos",
    status: "Últimas unidades",
    image: defaultImage,
    cardInstallments: { 3: 843733, 6: 448233, 12: 256133, 18: 199633 },
    updatedAt: importedAt,
  },
  {
    id: "moto-honda-dax-70",
    brand: "Honda",
    model: "Dax 70",
    category: "Cub",
    price: 2500,
    currency: "USD",
    cost: 0,
    stock: 1,
    branch: "RE Motos",
    status: "Últimas unidades",
    image: defaultImage,
    notes: "Precio del PDF expresado en dolares.",
    updatedAt: importedAt,
  },
  {
    id: "moto-ika-110-slalom-full",
    brand: "Ika",
    model: "110 Slalom full",
    category: "Cub",
    price: 1670000,
    currency: "ARS",
    cost: 0,
    stock: 1,
    branch: "RE Motos",
    status: "Últimas unidades",
    image: defaultImage,
    cardInstallments: { 3: 623466, 6: 331216, 12: 189266, 18: 147516 },
    updatedAt: importedAt,
  },
  {
    id: "moto-ika-110-slalom-base",
    brand: "Ika",
    model: "110 Slalom base",
    category: "Cub",
    price: 1530000,
    currency: "ARS",
    cost: 0,
    stock: 1,
    branch: "RE Motos",
    status: "Últimas unidades",
    image: defaultImage,
    cardInstallments: { 3: 570000, 6: 303500, 12: 173000, 18: 135150 },
    updatedAt: importedAt,
  },
  {
    id: "moto-ika-spot-base-150",
    brand: "Ika",
    model: "Spot base 150",
    category: "Street",
    price: 2280000,
    currency: "ARS",
    cost: 0,
    stock: 1,
    branch: "RE Motos",
    status: "Últimas unidades",
    image: defaultImage,
    cardInstallments: { 3: 851200, 6: 452200, 12: 258400, 18: 201400 },
    updatedAt: importedAt,
  },
  {
    id: "moto-motomel-serie-2-full-150",
    brand: "Motomel",
    model: "Serie 2 full 150",
    category: "Street",
    price: 2950000,
    currency: "ARS",
    cost: 0,
    stock: 1,
    branch: "RE Motos",
    status: "Últimas unidades",
    image: defaultImage,
    cardInstallments: { 3: 1101333, 6: 585083, 12: 334333, 18: 260583 },
    updatedAt: importedAt,
  },
  {
    id: "moto-hero-xpulse-200",
    brand: "Hero",
    model: "Xpulse 200",
    category: "Trail",
    price: 4650000,
    currency: "ARS",
    cost: 0,
    stock: 1,
    branch: "RE Motos",
    status: "Últimas unidades",
    image: defaultImage,
    cardInstallments: { 3: 1736000, 6: 922250, 12: 527000, 18: 410750 },
    updatedAt: importedAt,
  },
  {
    id: "moto-kove-350r",
    brand: "Kove",
    model: "350R",
    category: "Deportiva",
    price: 10200000,
    currency: "ARS",
    cost: 0,
    stock: 1,
    branch: "RE Motos",
    status: "Últimas unidades",
    image: defaultImage,
    updatedAt: importedAt,
  },
  {
    id: "moto-ika-durban-150",
    brand: "Ika",
    model: "Durban 150",
    category: "Street",
    price: 2510000,
    currency: "ARS",
    cost: 0,
    stock: 1,
    branch: "RE Motos",
    status: "Últimas unidades",
    image: defaultImage,
    cardInstallments: { 3: 937066, 6: 497816, 12: 284466, 18: 221716 },
    updatedAt: importedAt,
  },
  {
    id: "moto-gilera-sahel-150",
    brand: "Gilera",
    model: "Sahel 150",
    category: "Trail",
    price: 3200000,
    currency: "ARS",
    cost: 0,
    stock: 1,
    branch: "RE Motos",
    status: "Últimas unidades",
    image: defaultImage,
    cardInstallments: { 3: 1194666, 6: 634666, 12: 362666, 18: 282266 },
    updatedAt: importedAt,
  },
  {
    id: "moto-gilera-smx",
    brand: "Gilera",
    model: "SMX",
    category: "Trail",
    price: 3600000,
    currency: "ARS",
    cost: 0,
    stock: 1,
    branch: "RE Motos",
    status: "Últimas unidades",
    image: defaultImage,
    cardInstallments: { 3: 1344000, 6: 714000, 12: 408000, 18: 318000 },
    updatedAt: importedAt,
  },
  {
    id: "moto-kove-525x",
    brand: "Kove",
    model: "525X",
    category: "Trail",
    price: 13967000,
    currency: "ARS",
    cost: 0,
    stock: 1,
    branch: "RE Motos",
    status: "Últimas unidades",
    image: defaultImage,
    updatedAt: importedAt,
  },
  {
    id: "moto-bmw-gs-1200",
    brand: "BMW",
    model: "GS 1200",
    category: "Trail",
    price: 12500,
    currency: "USD",
    cost: 0,
    stock: 1,
    branch: "RE Motos",
    status: "Últimas unidades",
    image: defaultImage,
    notes: "Precio del PDF expresado en dolares.",
    updatedAt: importedAt,
  },
];

export const demoData: AgencyData = {
  motorcycles: priceListMotorcycles,
  customers: [],
  sales: [],
  financings: [],
  branches: [
    {
      id: "suc-re-motos",
      name: "RE Motos",
      city: "Gualeguaychú",
      address: "Gualeguaychú, Entre Ríos",
      manager: "Ruso",
      stock: priceListMotorcycles.reduce(
        (total, motorcycle) => total + motorcycle.stock,
        0,
      ),
      monthlySales: 0,
      todaySales: 0,
    },
  ],
  monthlySales: [
    { month: "Ene", total: 0 },
    { month: "Feb", total: 0 },
    { month: "Mar", total: 0 },
    { month: "Abr", total: 0 },
    { month: "May", total: 0 },
    { month: "Jun", total: 0 },
  ],
  financingBreakdown: [
    { label: "Tarjeta 3", count: 0, color: "#2563eb" },
    { label: "Tarjeta 6", count: 0, color: "#10b981" },
    { label: "Tarjeta 12", count: 0, color: "#7c3aed" },
    { label: "Tarjeta 18", count: 0, color: "#f97316" },
  ],
  activityLog: [
    {
      id: "act-lista-precios-inicial",
      type: "stock",
      workerName: "Sistema",
      description:
        "Lista inicial de modelos y precios importada desde el PDF de RE Motos.",
      createdAt: importedAt,
    },
  ],
  lastUpdated: importedAt,
};
